# #####################################################################
# Automatically generated by qmake (2.01a) Tue Mar 16 23:01:52 2010
# #####################################################################
QT += widgets

TEMPLATE = app
TARGET = testsprite
DEPENDPATH += .
INCLUDEPATH += .
RESOURCES += testsprite.qrc

# Input
SOURCES += main.cpp \
    gamecanvas.cpp \
    sprite.cpp
HEADERS += gamecanvas.h \
    sprite.h
